name: build

on:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build
        run: |
          ls -al ${{ env.ANDROID_SDK_ROOT }}/ndk/27.1.12297006/toolchains/llvm/prebuilt/
          ls -al ${{ env.ANDROID_SDK_ROOT }}/cmake/3.22.1/bin/cmake
