name: build

on:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e
          add-to-path: false

      - name: Build
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Build
        run: |
          chmod +x ./version.sh
          ./version.sh
          cd build/android/ndk/jni
          ${{ env.ANDROID_NDK_HOME }}/ndk-build
          ls -al ./
          cd ../../../../
          ls -al ./
          ls -al ./build/
          ls -al ./build/android/
          ls -al ./build/android/ndk/

      - uses: actions/upload-artifact@v4
        with:
          name: avs3
          path: ./build/android/ndk/libs/
