name: build

on:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build
        run: |
          ls -al ${{ env.ANDROID_SDK_ROOT }}/ndk/27.1.12297006/toolchains/llvm/prebuilt/linux-x86_64
          ls -al ${{ env.ANDROID_SDK_ROOT }}/cmake/3.22.1/bin/cmake
          
          ANDROID_NDK_HOME=${{ env.ANDROID_SDK_ROOT }}/ndk/27.1.12297006
          TOOLCHAIN_PREFIX=${{ env.ANDROID_SDK_ROOT }}/ndk/27.1.12297006/toolchains/llvm/prebuilt/linux-x86_64
          CMAKE_EXECUTABLE=${{ env.ANDROID_SDK_ROOT }}/cmake/3.22.1/bin/cmake
          BASE_DIR=$(cd "$(dirname "$0")" && pwd)
          BUILD_DIR=$BASE_DIR/build
          mkdir -p $BUILD_DIR
          ABI=armeabi-v7a
          CMAKE_BUILD_DIR=$BASE_DIR/avs3_build_$ABI
          mkdir -p $CMAKE_BUILD_DIR
          cd $CMAKE_BUILD_DIR
          ${{ env.ANDROID_SDK_ROOT }}/cmake/3.22.1/bin/cmake .. \  
          -DCMAKE_VERBOSE_MAKEFILE=ON \ 
          -DANDROID_PLATFORM=$ANDROID_PLATFORM \
          -DANDROID_ABI=$ABI \
          -DCMAKE_SYSTEM_PROCESSOR=$ABI \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
          -DCMAKE_INSTALL_PREFIX=$BUILD_DIR/external/$ABI \
          -DCOMPILE_10BIT=1 \
          -DBUILD_SHARED_LIBS=1 \
          -DCMAKE_USE_PTHREADS_INIT=0
          
