name: build-v8a

on:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e
          add-to-path: false

      - name: Build
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          CMAKE_EXECUTABLE=$ANDROID_HOME/cmake/3.18.1/bin/cmake
          ANDROID_NDK_HOME=${{ env.ANDROID_NDK_HOME }}
          BASE_DIR=$(pwd)
          ls -al $BASE_DIR
          BUILD_DIR=$BASE_DIR/build
          mkdir -p $BUILD_DIR
          ls -al $BUILD_DIR
          ABI=arm64-v8a
          CMAKE_BUILD_DIR=$BASE_DIR/avs3_build_$ABI
          mkdir -p $CMAKE_BUILD_DIR
          ls -al $BASE_DIR
          cd $CMAKE_BUILD_DIR
          mkdir -p $BUILD_DIR/external/$ABI
          ls -al $BUILD_DIR/external
          ANDROID_PLATFORM=21
          "$CMAKE_EXECUTABLE" .. -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_SYSTEM_NAME=Android -DCMAKE_SYSTEM_VERSION=${ANDROID_PLATFORM} -DCMAKE_ANDROID_ARCH_ABI=$ABI -DANDROID_PLATFORM=${ANDROID_PLATFORM} -DANDROID_ABI=$ABI -DPROJECT_ABI=$ABI -DANDROID_NDK=$ANDROID_NDK_HOME -DCMAKE_ANDROID_NDK=$ANDROID_NDK_HOME -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DCMAKE_INSTALL_PREFIX=$BUILD_DIR/external/$ABI -DCOMPILE_10BIT=1 -DBUILD_SHARED_LIBS=1
          ls -al ..
          make
          make install
          
